# Use root/example as user/password credentials
version: '3.8'

services:
    mongo:
        image: mongo
        hostname: mongo
        restart: always
        container_name: mongo
        ports:
            - 27017:27017
        extra_hosts:
            - 'localhost:0.0.0.0'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_REPLICA_SET_NAME: rs0
        command: '--bind_ip_all --keyFile /opt/keyfile/keyfile --replSet rs0 --port 27017'
        volumes:
            - mongo1:/data/db
            - ./:/opt/keyfile/
        networks:
            - mongo-network
    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #         - 8081:8081
    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: example
    #         ME_CONFIG_MONGODB_URL: mongodb://root:example@localhost:27017
volumes:
    mongo1:
networks:
    mongo-network:
        driver: bridge
